set @iUUID  = 'hwibf852-91d1-4373-b9f7-979ce0e907c3';
set @pUUID  = 'hwpbf852-91d1-4373-b9f7-979ce0e907c3';
set @rUUID  = 'hwrbf852-91d1-4373-b9f7-979ce0e907c3';
set @cUUID  = 'hwcbf852-91d1-4373-b9f7-979ce0e907c3';
set @cvUUID = 'hwcvf852-91d1-4373-b9f7-979ce0e907c3';
set @ccUUID = 'hwccf852-91d1-4373-b9f7-979ce0e907c3';

insert ignore into ContentRepository (uuid, repositoryType, prefix, path, institutionUUID) values (@rUUID, 'FS', 'repository/hwrbf852-91d1-4373-b9f7-979ce0e907c3','<invalid path>', @iUUID);
insert ignore into Institution values(@iUUID,'helloworld',null,'http://localhost:8888/Kornell.nocache.html?institution=helloworld',0,'Hello World University',now(),1,'_blue',0,0,'monthly','DEFAULT',null,0,1,@rUUID, 'America/New_York', 'support@helloworlduni.com');
update Institution set terms = '<p><span style="color: white">Welcome to the Hello World University!</span></p><p>Here you would find the terms of use for a course on the platform</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum iaculis eros tellus, in volutpat mauris viverra vel. Proin egestas enim eget arcu condimentum, at fermentum tellus finibus. Vivamus convallis enim sed magna rhoncus, eu ultricies ipsum consequat. Mauris eget sollicitudin mi. Integer scelerisque odio sem, vitae auctor enim vehicula sit amet. Sed leo felis, tempus nec mattis eget, elementum ac nibh. Sed semper eros dapibus magna lobortis rhoncus. Sed ornare rhoncus est, et rhoncus ante mattis ut. Sed porta tellus viverra sem interdum hendrerit. Morbi odio leo, varius sed dignissim a, mattis vel nulla. Aliquam purus mauris, mattis id ligula vitae, auctor mattis tortor. Suspendisse et ligula at felis vestibulum finibus. Mauris sagittis maximus eros ac faucibus. Morbi quis nunc fringilla, accumsan diam posuere, pulvinar ex. Vivamus ornare, ex in pellentesque semper, purus quam sodales mi, vel volutpat nisi massa consequat sem.</p>
<p>Proin ut elementum magna. Duis quis arcu id nulla consectetur sodales. Nunc nec odio aliquam nunc pellentesque pharetra at in sapien. Duis finibus dictum magna, nec aliquet risus ultrices quis. Proin ornare mollis ullamcorper. Nam pulvinar luctus enim efficitur porttitor. Cras at consectetur ligula. Proin cursus nibh in leo malesuada, non elementum lorem consequat. Integer erat leo, sollicitudin ornare ornare quis, gravida ut erat. Donec in nisi id tortor viverra elementum. Nulla quis dolor ut augue condimentum dignissim ut non nibh. In ac risus accumsan urna gravida luctus vel eget enim.</p>
<p>Vestibulum vitae aliquam dui. Quisque suscipit volutpat odio, ut vehicula libero rutrum sit amet. Integer sapien massa, sodales quis porta quis, dapibus eget turpis. Curabitur quis fringilla augue. Morbi purus eros, sagittis ac luctus ac, ultricies accumsan libero. Nam at turpis mattis, pulvinar enim sed, tempor arcu. Nam finibus lacinia magna porttitor eleifend. Vestibulum est elit, convallis at tempor in, pulvinar aliquet odio. Etiam magna ante, bibendum a nisl nec, consectetur tempor felis. Morbi nibh risus, vehicula viverra mauris et, sollicitudin cursus nisi. Nulla auctor tortor dolor, vel scelerisque erat tincidunt facilisis.</p>
<p>Ut sed nunc sed nisi faucibus varius. Suspendisse non magna ipsum. Nulla vehicula sapien eget interdum pretium. Nulla a elementum massa, ut placerat metus. Curabitur in vulputate turpis, sit amet dignissim eros. Fusce dictum purus nec eros tincidunt, quis egestas nulla fermentum. Phasellus rhoncus aliquam aliquam.</p>
<p>Pellentesque venenatis justo a tortor sollicitudin pretium. Sed iaculis in ante in tempor. Quisque justo quam, scelerisque eget erat ac, dictum euismod mi. Integer at metus id quam porta eleifend ut vitae ligula. Cras tortor ipsum, suscipit non suscipit in, condimentum quis felis. Quisque dictum, tortor sed efficitur dignissim, lectus quam lacinia sapien, ac accumsan nunc mauris quis ipsum. Etiam ultricies ullamcorper nibh sed pellentesque.</p>' where uuid = @iUUID;

insert ignore into InstitutionHostName (uuid, hostName, institutionUUID) values ('auce860a-b36c-11e6-bd35-768f6b6cd8f9','staging.helloworlduni.com', @iUUID);
insert ignore into InstitutionHostName (uuid, hostName, institutionUUID) values ('auce8614-b36c-11e6-bd35-768f6b6cd8f9', 'develop.helloworlduni.com', @iUUID);
insert ignore into InstitutionHostName (uuid, hostName, institutionUUID) values ('auce8615-b36c-11e6-bd35-768f6b6cd8f9','helloworlduni.com',@iUUID);

insert ignore into Person values (@pUUID,'Hello World Admin',NULL,'admin@helloworlduni.com',NULL,NULL,NULL,NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,@iUUID,null,'email',NULL,1,1);
insert ignore into Password values ('admin@helloworlduni.com','$2a$10$ovZmMwCwvsvvEidNhVWUpeaIBrrIZWfeIRJnCV6CGirQWHC8fs36K',@pUUID,NULL,'b5697q30-c77c-18e5-9857-10bf4818bdd1',@iUUID);
insert ignore into Role values ('7f54er69-c77c-11e5-9q57-10bf4818bdd1','platformAdmin',@iUUID,NULL,@pUUID);

insert ignore into Course values (@cUUID,'helloworld','Hello World!','Learn about Kornell and how it works!','{"topics":[{"index":"1","title":"Welcome!"}],"hints":[{"type":"fa fa-clock-o","text":"Estimated time: 30 minutes."},{"type":"fa fa-certificate","text":"Course with certificate"},{"type":"fa fa-question-circle","text":"If you need to contact us, click help in the menu above."},{"type":"fa fa-warning","text":"This course contains video and audio, make sure your device can play them."}],"infos":[{"type":"About the course","text":"Kornell is a complicated platform. This easy course is an example of all the features it has to offer."}]}', @iUUID,0);
insert ignore into CourseVersion values (@cvUUID,'HelloWorld - Version 0.1',@cUUID,now(),'helloWorld/v0.1','KNL',0,null,1,null);
insert ignore into CourseClass values (@ccUUID,'Hello World - First class',@cvUUID, @iUUID,1,60,20,now(),@pUUID,'active',0,0,'email',null,1,0,0,1,0,null,null);
