package kornell.core.entity;

public enum EmailTemplateType {
    BATCH_ENROLLMENT_CONFIRMATION,
    ENROLLMENT_CONFIRMATION,
    SIGNUP_CONFIRMATION,
    PASSWORD_RESET,
    NEW_SUPPORT_CHAT_THREAD,
    NEW_INSTITUTION_SUPPORT_CHAT_THREAD,
    NEW_PLATFORM_SUPPORT_CHAT_THREAD,
    NEW_TUTORING_CHAT_THREAD,
    ESPINAFRE_REMINDER,
    CLASS_COMPLETION
}
